version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"

    volumes:
      - ./mongo-data:/data/db
    command: mongod --noauth --wiredTigerCacheSizeGB 1.
    networks: 
      - mongo-network
  backend: 
    build: ./
    container_name: backend
    restart: unless-stopped
    ports: 
      - 3000:3000
    volumes:
      - ./.env:/app/.env
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    networks: 
      - mongo-network

networks: 
  mongo-network:
    driver: bridge
